#!/bin/bash
# LCARS Kanban System Installer
# Sets up kanban boards, LCARS web UI, backup system, and port management

set -euo pipefail

# Source common utilities
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/../lib/common.sh"

#──────────────────────────────────────────────────────────────────────────────
# Constants
#──────────────────────────────────────────────────────────────────────────────

KANBAN_BACKUP_LABEL="com.devteam.kanban-backup"
KANBAN_BACKUP_INTERVAL=900  # 15 minutes (in seconds)
DEFAULT_LCARS_PORT=8080

#──────────────────────────────────────────────────────────────────────────────
# Helper Functions
#──────────────────────────────────────────────────────────────────────────────

# Get kanban directory for a specific team
get_team_kanban_dir() {
    local team="$1"

    case "$team" in
        academy)
            echo "$DEV_TEAM_DIR/kanban"
            ;;
        ios)
            echo "/Users/Shared/Development/Main Event/MainEventApp-iOS/kanban"
            ;;
        android)
            echo "/Users/Shared/Development/Main Event/MainEventApp-Android/kanban"
            ;;
        firebase)
            echo "/Users/Shared/Development/Main Event/MainEventApp-Functions/kanban"
            ;;
        command)
            echo "/Users/Shared/Development/Main Event/dev-team/kanban"
            ;;
        dns)
            echo "/Users/Shared/Development/DNSFramework/kanban"
            ;;
        *)
            # Unknown teams go to dev-team (safe default)
            echo "$DEV_TEAM_DIR/kanban"
            ;;
    esac
}

# Initialize empty kanban board for a team
init_kanban_board() {
    local team="$1"
    local kanban_dir
    kanban_dir="$(get_team_kanban_dir "$team")"

    local board_file="$kanban_dir/${team}-board.json"

    # Create kanban directory if it doesn't exist
    mkdir -p "$kanban_dir"
    mkdir -p "$kanban_dir/config"
    mkdir -p "$kanban_dir/releases"

    # Only create board file if it doesn't already exist
    if [ ! -f "$board_file" ]; then
        info "Creating empty kanban board for team: $team"

        # Use template to create initial board structure
        local template="$INSTALL_ROOT/share/templates/kanban/board-template.json"
        if [ -f "$template" ]; then
            sed -e "s/{{TEAM}}/$team/g" "$template" > "$board_file"
        else
            # Fallback to minimal structure
            cat > "$board_file" << EOF
{
  "name": "$team",
  "items": [],
  "backlog": [],
  "blocked": []
}
EOF
        fi

        success "Created kanban board: $board_file"
    else
        info "Kanban board already exists: $board_file (skipping)"
    fi
}

# Install kanban-helpers.sh
install_kanban_helpers() {
    local template="$INSTALL_ROOT/share/templates/kanban/kanban-helpers.template.sh"
    local target="$DEV_TEAM_DIR/kanban-helpers.sh"

    if [ ! -f "$template" ]; then
        error "Template not found: $template"
        return 1
    fi

    info "Installing kanban helper functions"

    # Substitute DEV_TEAM_DIR in template
    sed -e "s|{{DEV_TEAM_DIR}}|$DEV_TEAM_DIR|g" \
        "$template" > "$target"

    chmod +x "$target"
    success "Installed: $target"
}

# Install kanban hooks
install_kanban_hooks() {
    local hooks_src="$INSTALL_ROOT/share/kanban-hooks"
    local hooks_dest="$DEV_TEAM_DIR/kanban-hooks"

    if [ ! -d "$hooks_src" ]; then
        warning "Kanban hooks not found at: $hooks_src (skipping)"
        return 0
    fi

    info "Installing kanban hooks"

    # Create hooks directory
    mkdir -p "$hooks_dest"

    # Copy all Python hook files
    cp -r "$hooks_src"/* "$hooks_dest/"

    # Make hook scripts executable
    chmod +x "$hooks_dest"/*.py 2>/dev/null || true

    success "Installed kanban hooks to: $hooks_dest"
}

# Install LCARS web UI
install_lcars_ui() {
    local lcars_src="$INSTALL_ROOT/share/lcars-ui"
    local lcars_dest="$DEV_TEAM_DIR/lcars-ui"

    if [ ! -d "$lcars_src" ]; then
        error "LCARS UI not found at: $lcars_src"
        return 1
    fi

    info "Installing LCARS web UI"

    # Create LCARS directory
    mkdir -p "$lcars_dest"

    # Copy all LCARS files recursively
    cp -r "$lcars_src"/* "$lcars_dest/"

    # Make server script executable
    chmod +x "$lcars_dest/server.py" 2>/dev/null || true
    chmod +x "$lcars_dest"/*.sh 2>/dev/null || true

    success "Installed LCARS UI to: $lcars_dest"
}

# Configure LCARS port
configure_lcars_port() {
    local port="${1:-$DEFAULT_LCARS_PORT}"
    local port_config="$DEV_TEAM_DIR/lcars-ui/lcars-target.js"

    info "Configuring LCARS port: $port"

    # Create simple port configuration file
    cat > "$port_config" << EOF
// LCARS Server Port Configuration
// Generated by dev-team installer
const LCARS_PORT = $port;
EOF

    # Also create a shell-readable version
    echo "$port" > "$DEV_TEAM_DIR/lcars-ui/.lcars-port"

    success "LCARS port configured: $port"
}

# Install port management files
install_port_management() {
    local ports_src="$INSTALL_ROOT/share/lcars-ports"
    local ports_dest="$DEV_TEAM_DIR/lcars-ports"

    info "Installing port management configuration"

    mkdir -p "$ports_dest"

    # Copy port configuration template
    local port_template="$INSTALL_ROOT/share/templates/kanban/port-config.json"
    if [ -f "$port_template" ]; then
        cp "$port_template" "$ports_dest/port-config.json"
    fi

    # If source ports exist, copy them as examples
    if [ -d "$ports_src" ]; then
        cp -r "$ports_src"/* "$ports_dest/" 2>/dev/null || true
    fi

    success "Installed port management to: $ports_dest"
}

# Install kanban backup system
install_kanban_backup() {
    local backup_script_src="$INSTALL_ROOT/share/scripts/kanban-backup.py"
    local backup_script_dest="$DEV_TEAM_DIR/kanban-backup.py"

    if [ ! -f "$backup_script_src" ]; then
        error "Backup script not found: $backup_script_src"
        return 1
    fi

    info "Installing kanban backup system"

    # Copy backup script
    cp "$backup_script_src" "$backup_script_dest"
    chmod +x "$backup_script_dest"

    # Create backup directory
    mkdir -p "$HOME/dev-team-backups/kanban"

    success "Installed backup script: $backup_script_dest"
}

# Install and load LaunchAgent for backup automation
install_backup_launchagent() {
    local plist_template="$INSTALL_ROOT/share/templates/kanban/backup-plist.template"
    local plist_dest="$HOME/Library/LaunchAgents/${KANBAN_BACKUP_LABEL}.plist"

    if [ ! -f "$plist_template" ]; then
        warning "LaunchAgent template not found: $plist_template (skipping)"
        return 0
    fi

    info "Installing backup LaunchAgent"

    # Create LaunchAgents directory if needed
    mkdir -p "$HOME/Library/LaunchAgents"

    # Substitute variables in template
    sed -e "s|{{USER_HOME}}|$HOME|g" \
        -e "s|{{DEV_TEAM_DIR}}|$DEV_TEAM_DIR|g" \
        -e "s|{{BACKUP_INTERVAL}}|$KANBAN_BACKUP_INTERVAL|g" \
        "$plist_template" > "$plist_dest"

    # Unload if already loaded (ignore errors)
    launchctl unload "$plist_dest" 2>/dev/null || true

    # Load the LaunchAgent
    if launchctl load "$plist_dest"; then
        success "Installed and loaded backup LaunchAgent"
        info "Backups will run every 15 minutes"
    else
        warning "Failed to load LaunchAgent (may need manual activation)"
    fi
}

# Uninstall backup LaunchAgent
uninstall_backup_launchagent() {
    local plist_file="$HOME/Library/LaunchAgents/${KANBAN_BACKUP_LABEL}.plist"

    if [ -f "$plist_file" ]; then
        info "Unloading backup LaunchAgent"
        launchctl unload "$plist_file" 2>/dev/null || true
        rm -f "$plist_file"
        success "Removed backup LaunchAgent"
    fi
}

# Test LCARS server startup
test_lcars_server() {
    local port="${1:-$DEFAULT_LCARS_PORT}"
    local server_script="$DEV_TEAM_DIR/lcars-ui/server.py"

    if [ ! -f "$server_script" ]; then
        warning "LCARS server not found, skipping test"
        return 0
    fi

    info "Testing LCARS server startup..."

    # Start server in background
    python3 "$server_script" "$port" &>/dev/null &
    local server_pid=$!

    # Wait a moment for startup
    sleep 2

    # Check if server is running
    if kill -0 "$server_pid" 2>/dev/null; then
        success "LCARS server started successfully on port $port"
        info "Access at: http://localhost:$port"

        # Stop the test server
        kill "$server_pid" 2>/dev/null || true
        return 0
    else
        warning "LCARS server failed to start (check port availability)"
        return 1
    fi
}

#──────────────────────────────────────────────────────────────────────────────
# Main Installation Function
#──────────────────────────────────────────────────────────────────────────────

install_kanban_system() {
    header "Installing LCARS Kanban System"

    # Get selected teams from config
    local teams=()
    if [ -f "$DEV_TEAM_DIR/.dev-team-config" ]; then
        # Read teams from config file
        while IFS= read -r team; do
            teams+=("$team")
        done < <(grep "^TEAM_" "$DEV_TEAM_DIR/.dev-team-config" | cut -d= -f2)
    fi

    # Default to academy if no teams configured
    if [ ${#teams[@]} -eq 0 ]; then
        teams=("academy")
    fi

    info "Setting up kanban boards for teams: ${teams[*]}"

    # Install core kanban components
    install_kanban_helpers || return 1
    install_kanban_hooks || return 1

    # Initialize kanban boards for each team
    for team in "${teams[@]}"; do
        init_kanban_board "$team"
    done

    # Install LCARS UI
    install_lcars_ui || return 1

    # Get LCARS port (ask user or use default)
    local lcars_port
    if prompt_yes_no "Use default LCARS port ($DEFAULT_LCARS_PORT)?" "y"; then
        lcars_port=$DEFAULT_LCARS_PORT
    else
        read -p "Enter LCARS port number: " -r lcars_port
        lcars_port="${lcars_port:-$DEFAULT_LCARS_PORT}"
    fi

    configure_lcars_port "$lcars_port" || return 1
    install_port_management || return 1

    # Install backup system
    install_kanban_backup || return 1

    # Ask about LaunchAgent
    if prompt_yes_no "Install automated backup LaunchAgent?" "y"; then
        install_backup_launchagent || warning "LaunchAgent installation failed"
    else
        info "Skipping LaunchAgent installation"
        info "You can manually run backups with: python3 $DEV_TEAM_DIR/kanban-backup.py"
    fi

    # Test LCARS server
    if prompt_yes_no "Test LCARS server startup?" "y"; then
        test_lcars_server "$lcars_port"
    fi

    success "LCARS Kanban System installed successfully"

    info ""
    info "Kanban System Ready:"
    info "  • Boards initialized for: ${teams[*]}"
    info "  • LCARS UI: http://localhost:$lcars_port"
    info "  • Backup system: Automated (every 15 min)"
    info "  • Helper functions: source $DEV_TEAM_DIR/kanban-helpers.sh"
    info ""
    info "To start LCARS server manually:"
    info "  python3 $DEV_TEAM_DIR/lcars-ui/server.py $lcars_port"
    info ""

    return 0
}

#──────────────────────────────────────────────────────────────────────────────
# Uninstall Function
#──────────────────────────────────────────────────────────────────────────────

uninstall_kanban_system() {
    header "Uninstalling LCARS Kanban System"

    # Unload LaunchAgent
    uninstall_backup_launchagent

    # Remove installed files
    info "Removing kanban system files"
    rm -f "$DEV_TEAM_DIR/kanban-helpers.sh"
    rm -rf "$DEV_TEAM_DIR/kanban-hooks"
    rm -rf "$DEV_TEAM_DIR/lcars-ui"
    rm -rf "$DEV_TEAM_DIR/lcars-ports"
    rm -f "$DEV_TEAM_DIR/kanban-backup.py"

    # Ask about board data
    if prompt_yes_no "Remove kanban board data?" "n"; then
        warning "This will delete all kanban boards and history!"
        if prompt_yes_no "Are you SURE?" "n"; then
            rm -rf "$DEV_TEAM_DIR/kanban"
            rm -rf "$HOME/dev-team-backups/kanban"
            success "Removed all kanban data"
        fi
    else
        info "Keeping kanban board data (can be manually removed later)"
    fi

    success "LCARS Kanban System uninstalled"

    return 0
}

#──────────────────────────────────────────────────────────────────────────────
# Export functions for setup wizard
#──────────────────────────────────────────────────────────────────────────────

export -f install_kanban_system
export -f uninstall_kanban_system
