#!/bin/bash
# Shell Environment Installer
# Sets up zsh integration, prompts, aliases, and secrets management

set -euo pipefail

# Source common utilities
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/../lib/common.sh"

#──────────────────────────────────────────────────────────────────────────────
# Constants
#──────────────────────────────────────────────────────────────────────────────

ZSHRC_MARKER_START="# >>> dev-team initialize >>>"
ZSHRC_MARKER_END="# <<< dev-team initialize <<<"
ZSHRC_BACKUP_SUFFIX=".dev-team-backup"

#──────────────────────────────────────────────────────────────────────────────
# Helper Functions
#──────────────────────────────────────────────────────────────────────────────

# Check if zshrc already has dev-team integration
has_zshrc_integration() {
    if [ ! -f "$HOME/.zshrc" ]; then
        return 1
    fi
    grep -q "$ZSHRC_MARKER_START" "$HOME/.zshrc"
}

# Add dev-team sourcing block to zshrc
add_zshrc_integration() {
    local zshrc="$HOME/.zshrc"

    # Create zshrc if it doesn't exist
    if [ ! -f "$zshrc" ]; then
        info "Creating new .zshrc file"
        touch "$zshrc"
    fi

    # Back up existing zshrc
    if [ ! -f "${zshrc}${ZSHRC_BACKUP_SUFFIX}" ]; then
        info "Backing up existing .zshrc to ${zshrc}${ZSHRC_BACKUP_SUFFIX}"
        cp "$zshrc" "${zshrc}${ZSHRC_BACKUP_SUFFIX}"
    fi

    # Add integration block
    info "Adding dev-team integration to .zshrc"
    cat >> "$zshrc" << EOF

$ZSHRC_MARKER_START
# Dev-Team Environment Loader
# Auto-generated by dev-team installer
if [ -f "$DEV_TEAM_DIR/share/dev-team-env.sh" ]; then
    source "$DEV_TEAM_DIR/share/dev-team-env.sh"
fi
$ZSHRC_MARKER_END
EOF

    success "Added dev-team integration to .zshrc"
}

# Remove dev-team integration from zshrc
remove_zshrc_integration() {
    local zshrc="$HOME/.zshrc"

    if [ ! -f "$zshrc" ]; then
        return 0
    fi

    if ! has_zshrc_integration; then
        return 0
    fi

    info "Removing dev-team integration from .zshrc"

    # Remove the block between markers (including markers)
    sed -i.tmp "/$ZSHRC_MARKER_START/,/$ZSHRC_MARKER_END/d" "$zshrc"
    rm -f "${zshrc}.tmp"

    success "Removed dev-team integration from .zshrc"
}

# Install environment loader script
install_env_loader() {
    local template="$INSTALL_ROOT/share/templates/dev-team-env.sh"
    local target="$DEV_TEAM_DIR/share/dev-team-env.sh"

    if [ ! -f "$template" ]; then
        error "Template not found: $template"
        return 1
    fi

    info "Installing environment loader"

    # Substitute variables in template
    sed -e "s|{{DEV_TEAM_DIR}}|$DEV_TEAM_DIR|g" \
        "$template" > "$target"

    chmod +x "$target"
    success "Installed environment loader"
}

# Install prompt configuration
install_prompt() {
    local template="$INSTALL_ROOT/share/templates/dev-team-prompt.sh"
    local target="$DEV_TEAM_DIR/share/dev-team-prompt.sh"

    if [ ! -f "$template" ]; then
        error "Template not found: $template"
        return 1
    fi

    info "Installing prompt configuration"

    # Copy template (no substitution needed for prompt)
    cp "$template" "$target"
    chmod +x "$target"

    success "Installed prompt configuration"
}

# Install shell aliases
install_aliases() {
    local aliases_dir="$DEV_TEAM_DIR/share/aliases"
    mkdir -p "$aliases_dir"

    info "Installing shell aliases"

    # Install each alias file
    for alias_file in agent-aliases.sh kanban-aliases.sh worktree-aliases.sh; do
        local template="$INSTALL_ROOT/share/templates/aliases/$alias_file"
        local target="$aliases_dir/$alias_file"

        if [ ! -f "$template" ]; then
            warning "Template not found: $template (skipping)"
            continue
        fi

        # Substitute variables in template
        sed -e "s|{{DEV_TEAM_DIR}}|$DEV_TEAM_DIR|g" \
            "$template" > "$target"

        chmod +x "$target"
    done

    success "Installed shell aliases"
}

# Install secrets template
install_secrets_template() {
    local template="$INSTALL_ROOT/share/templates/secrets.env.template"
    local target="$DEV_TEAM_DIR/secrets.env.template"
    local secrets_file="$DEV_TEAM_DIR/secrets.env"

    if [ ! -f "$template" ]; then
        error "Template not found: $template"
        return 1
    fi

    info "Installing secrets template"

    # Copy template
    cp "$template" "$target"

    # Check if actual secrets file exists
    if [ -f "$secrets_file" ]; then
        warning "Secrets file already exists at $secrets_file"
        info "Review $target for expected variables"
    else
        warning "No secrets file found"
        info "Copy $target to $secrets_file and populate with your credentials"
        info "NEVER commit the actual secrets.env file to git"
    fi

    success "Installed secrets template"
}

#──────────────────────────────────────────────────────────────────────────────
# Main Installation Function
#──────────────────────────────────────────────────────────────────────────────

install_shell_environment() {
    header "Installing Shell Environment"

    # Check if already installed
    if has_zshrc_integration; then
        warning "Shell integration already exists in .zshrc"
        if ! prompt_yes_no "Reinstall shell environment?" "n"; then
            info "Skipping shell environment installation"
            return 0
        fi
        # Remove and reinstall
        remove_zshrc_integration
    fi

    # Create necessary directories
    mkdir -p "$DEV_TEAM_DIR/share"

    # Install components
    install_env_loader || return 1
    install_prompt || return 1
    install_aliases || return 1
    install_secrets_template || return 1

    # Add zshrc integration
    add_zshrc_integration || return 1

    success "Shell environment installed successfully"

    info ""
    info "Next steps:"
    info "  1. Review secrets template: $DEV_TEAM_DIR/secrets.env.template"
    info "  2. Create secrets file: cp secrets.env.template secrets.env"
    info "  3. Populate secrets.env with your credentials"
    info "  4. Reload your shell: source ~/.zshrc"
    info ""

    return 0
}

#──────────────────────────────────────────────────────────────────────────────
# Uninstall Function
#──────────────────────────────────────────────────────────────────────────────

uninstall_shell_environment() {
    header "Uninstalling Shell Environment"

    # Remove zshrc integration
    remove_zshrc_integration

    # Remove installed files
    info "Removing shell environment files"
    rm -f "$DEV_TEAM_DIR/share/dev-team-env.sh"
    rm -f "$DEV_TEAM_DIR/share/dev-team-prompt.sh"
    rm -rf "$DEV_TEAM_DIR/share/aliases"
    rm -f "$DEV_TEAM_DIR/secrets.env.template"

    success "Shell environment uninstalled"

    # Restore backup if it exists
    if [ -f "$HOME/.zshrc${ZSHRC_BACKUP_SUFFIX}" ]; then
        info "Backup available at: $HOME/.zshrc${ZSHRC_BACKUP_SUFFIX}"
        if prompt_yes_no "Restore backup?" "n"; then
            cp "$HOME/.zshrc${ZSHRC_BACKUP_SUFFIX}" "$HOME/.zshrc"
            success "Restored .zshrc from backup"
        fi
    fi

    return 0
}

#──────────────────────────────────────────────────────────────────────────────
# Export functions for setup wizard
#──────────────────────────────────────────────────────────────────────────────

# This script is sourced by the setup wizard, so export the functions
export -f install_shell_environment
export -f uninstall_shell_environment
